#ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Example' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix for React Native 0.82 Folly coroutine issue
    # https://github.com/facebook/react-native/issues/37748
    # Apply to all Pod targets
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= '$(inherited)'
        unless config.build_settings['OTHER_CPLUSPLUSFLAGS'].include?('FOLLY_CFG_NO_COROUTINES')
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] += ' -DFOLLY_CFG_NO_COROUTINES=1'
        end
      end
    end
    
    # Also apply to the main app target (Example)
    app_project_path = File.join(File.dirname(installer.sandbox.root), 'Example.xcodeproj')
    app_project = Xcodeproj::Project.open(app_project_path)
    app_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= '$(inherited)'
        unless config.build_settings['OTHER_CPLUSPLUSFLAGS'].to_s.include?('FOLLY_CFG_NO_COROUTINES')
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = "#{config.build_settings['OTHER_CPLUSPLUSFLAGS']} -DFOLLY_CFG_NO_COROUTINES=1".strip
        end
      end
    end
    app_project.save
  end
end
